version: '3'

services:
  web:
    build: ./
    command: gunicorn shortner_app.wsgi:application --bind 0.0.0.0:6500
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 6500
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 6500:6500
    depends_on:
      - web
  

volumes:
  postgres_data:
  static_volume:
  media_volume: